const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const escapeHtml = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state = {
  view:'home', architect:false, health:{}, payments:[], audit:[], outbox:null,
  experiences:[], event:null, holds:[], currentHold:null, holdTimer:null,
  credential:JSON.parse(localStorage.getItem('bp-travel-credential')||'null'),
  offline:false, split:null, trace:JSON.parse(localStorage.getItem('bp-trace')||'[]')
};
const serviceMeta={
  payments:{name:'payments-api',data:'MariaDB',route:'/api/payments'},
  audit:{name:'audit-api',data:'MongoDB audit',route:'/api/audit'},
  experiences:{name:'experiences-api',data:'MongoDB experiences',route:'/api/experiences'},
  travel:{name:'travel-benefits-api',data:'MongoDB travel',route:'/api/travel'},
  events:{name:'events-api',data:'PostgreSQL + Redis',route:'/api/events'},
  'social-split':{name:'social-split-api',data:'PostgreSQL',route:'/api/splits'}
};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function trace(action,path,status='OK',detail=''){state.trace.unshift({time:new Date().toLocaleTimeString('es-EC',{hour12:false}),action,path,status,detail});state.trace=state.trace.slice(0,30);localStorage.setItem('bp-trace',JSON.stringify(state.trace));renderTrace()}
function renderTrace(){const el=$('#traceLog');if(!state.trace.length){el.innerHTML='<div class="empty-state">Interactúa con la aplicación para generar evidencia.</div>';return}el.innerHTML=state.trace.map(t=>`<div class="trace-entry"><time>${t.time}</time><div><strong>${escapeHtml(t.action)}</strong><small>${escapeHtml(t.path)}${t.detail?' · '+escapeHtml(t.detail):''}</small></div><b>${escapeHtml(t.status)}</b></div>`).join('')}
async function request(url,options={}){if(state.offline && url.startsWith('/api/travel')) throw new Error('OFFLINE');const start=performance.now();const r=await fetch(url,options);const ms=Math.round(performance.now()-start);if(!r.ok){const text=await r.text();throw Object.assign(new Error(text||`${r.status}`),{status:r.status,ms})}const ct=r.headers.get('content-type')||'';const data=ct.includes('json')?await r.json():await r.text();return {data,ms,status:r.status}}
function goto(view){state.view=view;$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#viewTitle').textContent={home:'Inicio',experiences:'Experiencias',travel:'Viajes',events:'Eventos',split:'Social Split',platform:'Platform'}[view]||view;if(view==='experiences')loadExperiences();if(view==='events')loadEvents();if(view==='platform'){refreshHealth();renderTrace()}window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>goto(b.dataset.view)));$$('[data-goto]').forEach(b=>b.addEventListener('click',()=>goto(b.dataset.goto)));
$('#clientMode').addEventListener('click',()=>setArchitect(false));$('#architectMode').addEventListener('click',()=>setArchitect(true));
function setArchitect(on){state.architect=on;document.body.classList.toggle('architect-mode',on);$('#clientMode').classList.toggle('active',!on);$('#architectMode').classList.toggle('active',on);toast(on?'Modo Arquitecto activado':'Modo Cliente activado')}
async function refreshHealth(){const keys=Object.keys(serviceMeta);const results=await Promise.allSettled(keys.map(k=>request('/health/'+k)));keys.forEach((k,i)=>state.health[k]=results[i].status==='fulfilled'&&results[i].value.data.status==='UP');const all=keys.every(k=>state.health[k]);$('#platformStatus').textContent=all?'ALL SYSTEMS OPERATIONAL':'DEGRADED';$('.pulse-dot').classList.toggle('ok',all);$('#sidebarDot').classList.toggle('ok',all);$('#sidebarHealth').textContent=all?'Operativo':'Degradado';renderHealth();return all}
function renderHealth(){const html=Object.entries(serviceMeta).map(([k,m])=>`<div class="health-item"><div><i class="health-dot ${state.health[k]?'ok':'bad'}"></i><span><strong>${m.name}</strong><small>${m.data}</small></span></div><small>${state.health[k]?'UP':'DOWN'}</small></div>`).join('');$('#homeHealth').innerHTML=html;$('#platformHealthGrid').innerHTML=Object.entries(serviceMeta).map(([k,m])=>`<article class="platform-health"><header><i class="health-dot ${state.health[k]?'ok':'bad'}"></i><strong>${m.name}</strong></header><small>${m.data}</small><small>${m.route}</small></article>`).join('')}
async function refreshCore(){const [p,a,o]=await Promise.allSettled([request('/api/payments'),request('/api/audit'),request('/api/outbox')]);if(p.status==='fulfilled')state.payments=p.value.data;if(a.status==='fulfilled')state.audit=a.value.data;if(o.status==='fulfilled')state.outbox=o.value.data;$('#paymentCount').textContent=state.payments.length;$('#auditCount').textContent=state.audit.length;$('#pendingCount').textContent=state.outbox?.pending??'—';renderPayments()}
function renderPayments(){const el=$('#recentPayments');if(!state.payments.length){el.innerHTML='<div class="empty-state">Aún no hay pagos. Crea uno desde Social Split o una experiencia.</div>';return}el.innerHTML=state.payments.slice(0,6).map(p=>`<div class="transaction"><span class="transaction-icon">$</span><div><strong>${escapeHtml(p.account||'BANKdragon')}</strong><small>${escapeHtml(p.createdAt||'Pago confirmado')}</small></div><div class="transaction-amount"><b>-$${Number(p.amount||0).toFixed(2)}</b><span>${escapeHtml(p.status||'CONFIRMED')}</span></div></div>`).join('')}
async function createPayment(amount,account='EC-LAB-4242'){const key=crypto.randomUUID();const r=await request('/api/payments',{method:'POST',headers:{'Content-Type':'application/json','X-Idempotency-Key':key},body:JSON.stringify({account,amount:Number(amount),currency:'USD'})});trace('Payment created','Browser → Nginx → payments-api → MariaDB','201',`${r.ms} ms`);await refreshCore();return r.data}
async function loadExperiences(){try{const r=await request('/api/experiences');state.experiences=r.data;trace('Experiences loaded','Browser → experiences-api → MongoDB','200',`${r.ms} ms`);$('#experiencesGrid').innerHTML=state.experiences.map((x,i)=>`<article class="experience-card"><div class="experience-visual"><div><span class="tiny-badge">${escapeHtml(x.city)}</span><h3>${escapeHtml(x.category)}</h3></div></div><div class="experience-body"><h3>${escapeHtml(x.name)}</h3><div class="experience-meta"><span>Capacidad ${x.capacity}</span><span>Beneficio BANKdragon</span><span>${escapeHtml(x.city)}</span></div><div class="experience-footer"><strong>$${Number(x.price).toFixed(2)}</strong><button data-buy-experience="${i}">Garantizar</button></div></div></article>`).join('');$$('[data-buy-experience]').forEach(b=>b.addEventListener('click',()=>buyExperience(Number(b.dataset.buyExperience))))}catch(e){$('#experiencesGrid').innerHTML=`<div class="result-box">No fue posible cargar experiences-api: ${escapeHtml(e.message)}</div>`}}
async function buyExperience(i){const x=state.experiences[i];try{const p=await createPayment(x.price,`EXP-${String(x.id).slice(0,8)}`);trace('Experience guaranteed','experiences-api ownership + payment reference','OK',`payment ${String(p.id||'').slice(0,8)}`);toast(`Garantía creada para ${x.name}`)}catch(e){toast('No fue posible crear la garantía') }}
function makeQr(seed='BANKDRAGON'){const chars=[...seed].map(c=>c.charCodeAt(0));let cells='';for(let i=0;i<81;i++){const on=((chars[i%chars.length]*(i+7)+i*13)%17)<8;cells+=`<i class="${on?'on':''}"></i>`}$('#credentialQr').innerHTML=cells}
function showCredential(c){if(!c)return;$('#credentialMember').textContent=c.memberId;$('#credentialBenefit').textContent=`${c.benefitCode} · expira ${new Date(c.expiresAt).toLocaleTimeString('es-EC',{hour12:false})}`;$('#credentialMode').textContent=c.mode;makeQr(c.signature||c.payload)}
$('#checkEligibility').addEventListener('click',async()=>{const member=$('#travelMember').value.trim();try{const e=await request(`/api/travel/eligibility/${encodeURIComponent(member)}`);trace('Eligibility checked','Browser → travel-benefits-api → MongoDB','200',`${e.ms} ms`);$('#eligibilityResult').innerHTML=e.data.eligible?`<b>Elegible</b> · ${e.data.remainingUses} accesos restantes`:'No elegible';if(e.data.eligible){const c=await request('/api/travel/credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({memberId:member,benefitCode:e.data.benefitCode})});state.credential=c.data;localStorage.setItem('bp-travel-credential',JSON.stringify(c.data));showCredential(c.data);trace('Signed credential issued','travel-benefits-api → HMAC credential','201',`${c.ms} ms`)}}catch(err){if(err.message==='OFFLINE'&&state.credential){$('#eligibilityResult').innerHTML='<b>OFFLINE</b> · usando credencial almacenada localmente';showCredential(state.credential);trace('Offline credential used','localStorage → local verification demo','OFFLINE')}else $('#eligibilityResult').textContent='Servicio no disponible'}})
$('#offlineToggle').addEventListener('change',e=>{state.offline=e.target.checked;$('#networkLabel').textContent=state.offline?'OFFLINE':'ONLINE';if(state.offline&&state.credential){showCredential(state.credential);$('#eligibilityResult').innerHTML='<b>Modo offline</b> · la credencial guardada sigue disponible.'}trace('Network mode changed','Client connectivity',state.offline?'OFFLINE':'ONLINE')});
async function loadEvents(){try{const r=await request('/api/events');state.event=r.data[0];if(!state.event)throw new Error('No event');$('#eventName').textContent=state.event.name;$('#eventVenue').textContent=`${state.event.venue} · capacidad ${state.event.seatCapacity}`;trace('Event loaded','Browser → events-api → PostgreSQL','200',`${r.ms} ms`);await refreshHolds();renderSeats()}catch(e){$('#eventName').textContent='Events API no disponible';}}
async function refreshHolds(){if(!state.event)return;try{const r=await request(`/api/events/${state.event.id}/holds`);state.holds=r.data}catch(e){state.holds=[]}}
function renderSeats(){const held=new Map(state.holds.map(h=>[h.seatId,h]));let html='';['A','B','C','D','E','F'].forEach(row=>{for(let n=1;n<=8;n++){const id=`${row}-${String(n).padStart(2,'0')}`;const h=held.get(id);const mine=state.currentHold?.seatId===id;html+=`<button class="seat ${mine?'mine':h?'held':''}" data-seat="${id}" ${h&&!mine?'title="Asiento reservado"':''}>${row}${n}</button>`}});$('#seatMap').innerHTML=html;$$('[data-seat]').forEach(b=>b.addEventListener('click',()=>holdSeat(b.dataset.seat)))}
async function holdSeat(seatId){if(!state.event)return;if(state.currentHold){toast('Libera tu HOLD actual antes de seleccionar otro');return}$('#selectedSeat').textContent=`Asiento ${seatId}`;try{const r=await request(`/api/events/${state.event.id}/holds`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seatId,memberId:'MEMBER-001'})});state.currentHold={...r.data,expiresAt:Date.now()+r.data.expiresInSeconds*1000};$('#holdResult').innerHTML=`<b>HOLD confirmado</b><br>${escapeHtml(String(r.data.holdId).slice(0,12))}…`;$('#releaseHold').disabled=false;trace('Seat HOLD created','Browser → events-api → Redis SET NX + TTL','201',`${r.ms} ms`);await refreshHolds();renderSeats();startCountdown()}catch(e){if(e.status===409){$('#holdResult').innerHTML='<b>HTTP 409</b> · otro usuario tomó el asiento primero.';trace('Seat HOLD conflict','events-api → Redis atomic check','409',`${e.ms||0} ms`);toast('Asiento ocupado: conflicto 409')}else $('#holdResult').textContent='No fue posible crear el HOLD'}}
function startCountdown(){clearInterval(state.holdTimer);const tick=()=>{if(!state.currentHold)return;const left=Math.max(0,Math.ceil((state.currentHold.expiresAt-Date.now())/1000));$('#holdCountdown').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(!left){clearInterval(state.holdTimer);state.currentHold=null;$('#releaseHold').disabled=true;$('#holdResult').textContent='TTL expirado: el asiento vuelve a estar disponible.';refreshHolds().then(renderSeats)}};tick();state.holdTimer=setInterval(tick,1000)}
$('#releaseHold').addEventListener('click',async()=>{if(!state.currentHold||!state.event)return;const h=state.currentHold;try{await request(`/api/events/${state.event.id}/holds/${h.holdId}?seatId=${encodeURIComponent(h.seatId)}`,{method:'DELETE'});trace('Seat HOLD released','events-api → Redis DEL','204');state.currentHold=null;clearInterval(state.holdTimer);$('#holdCountdown').textContent='--:--';$('#selectedSeat').textContent='Selecciona un asiento';$('#holdResult').textContent='HOLD liberado correctamente.';$('#releaseHold').disabled=true;await refreshHolds();renderSeats()}catch(e){toast('No fue posible liberar el HOLD')}})
const memberNames=['ANA-002','CARLOS-003','MARIA-004','DIEGO-005'];
$('#createSplit').addEventListener('click',async()=>{const total=Number($('#splitTotal').value);const count=Number($('#splitPeople').value);try{let r=await request('/api/splits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hostMemberId:'MEMBER-001',totalAmount:total,currency:'USD'})});state.split=r.data;const share=Number((total/count).toFixed(2));for(let i=0;i<count;i++){r=await request(`/api/splits/${state.split.id}/participants`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({memberId:i===0?'MEMBER-001':memberNames[i-1],shareAmount:share})});state.split=r.data}trace('Split session created','Browser → social-split-api → PostgreSQL','201',`${count} participants`);renderSplit();$('#splitMessage').innerHTML='<b>Sesión creada.</b> Autoriza cada participante con un pago real.'}catch(e){$('#splitMessage').textContent='No fue posible crear la sesión: '+e.message}})
function renderSplit(){if(!state.split)return;$('#splitSessionTitle').textContent=`Sesión ${String(state.split.id).slice(0,8)}`;$('#splitStatus').textContent=state.split.status;const ps=state.split.participants||[];const authorized=ps.filter(p=>p.authorized).length;const paid=ps.filter(p=>p.authorized).reduce((s,p)=>s+Number(p.shareAmount),0);$('#splitProgressBar').style.width=`${ps.length?authorized/ps.length*100:0}%`;$('#splitProgressText').textContent=`$${paid.toFixed(2)} / $${Number(state.split.totalAmount).toFixed(2)}`;$('#splitParticipants').innerHTML=ps.map(p=>`<div class="participant"><div><strong>${escapeHtml(p.memberId)}</strong><small>${p.authorized?'Autorizado · '+escapeHtml(p.paymentReference||''):'Esperando autorización'}</small></div><span class="amount">$${Number(p.shareAmount).toFixed(2)}</span><button class="${p.authorized?'authorized':''}" data-authorize="${p.id}" ${p.authorized?'disabled':''}>${p.authorized?'✓ Pagado':'Autorizar'}</button></div>`).join('');$$('[data-authorize]').forEach(b=>b.addEventListener('click',()=>authorizeParticipant(b.dataset.authorize)));$('#closeSplit').disabled=!(ps.length&&ps.every(p=>p.authorized)&&state.split.status!=='COMPLETED')}
async function authorizeParticipant(participantId){const p=state.split.participants.find(x=>x.id===participantId);try{const payment=await createPayment(p.shareAmount,`SPLIT-${String(state.split.id).slice(0,8)}`);const r=await request(`/api/splits/${state.split.id}/participants/${participantId}/authorize`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paymentReference:payment.id||`PAY-${crypto.randomUUID()}`})});state.split=r.data;trace('Participant authorized','payments-api reference → social-split-api','200',p.memberId);renderSplit()}catch(e){toast('Autorización falló')}}
$('#closeSplit').addEventListener('click',async()=>{try{const r=await request(`/api/splits/${state.split.id}/close`,{method:'POST'});state.split=r.data;trace('Split completed','social-split-api invariant: all authorized','200');renderSplit();toast('Cuenta colaborativa completada')}catch(e){toast('La sesión todavía no puede cerrarse')}})
function portUrl(port){const {protocol,hostname}=location;if(hostname.endsWith('.app.github.dev'))return `${protocol}//${hostname.replace(/-\d+\.app\.github\.dev$/,`-${port}.app.github.dev`)}`;return `${protocol}//${hostname}:${port}`}
$$('[data-port]').forEach(b=>b.addEventListener('click',()=>window.open(portUrl(b.dataset.port),'_blank','noopener')));$$('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{await navigator.clipboard.writeText(b.dataset.copy);toast('Comando copiado')}));
$('#clearTrace').addEventListener('click',()=>{state.trace=[];localStorage.removeItem('bp-trace');renderTrace()});$('#refreshAll').addEventListener('click',()=>bootstrap(true));
async function bootstrap(showToast=false){await Promise.all([refreshHealth(),refreshCore()]);showCredential(state.credential);renderTrace();if(showToast)toast('Datos actualizados')}
bootstrap();setInterval(()=>{refreshHealth();refreshCore()},15000);
