server:
  port: 8083
spring:
  application:
    name: experiences-api
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:mongo_local@localhost:27017/experiences?authSource=admin}
management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
  endpoint.health.probes.enabled: true
